name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install devbox
      uses: jetpack-io/devbox-install-action@v0.4.0
      with:
        enable-cache: 'true'
    - name: Build
      run: devbox run build
    - name: Run tests
      run: devbox run test
